### ISSUE TITLE
non-matched sample_name, tumour_bam and normal_bam from the html report 

### ISSUE THREAD

**Issue by selmapichot** [epi2me-labs/wf-somatic-variation#24] opened 2024-06-06 18:13 UTC
### Operating System

Other Linux (please specify below)

### Other Linux

rocky linux 8.9

### Workflow Version

v1.1.0-g5851e21

### Workflow Execution

Command line (Cluster)

### CLI command run

nextflow run epi2me-labs/wf-somatic-variation --bam_normal "/rds/project/sorted_aligned_TB21.06450_normal.bam" --bam_tumor "/rds/project/sorted_aligned_TB21.06450_t1.bam" --ref "/rds/project/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" --snv --mod --sample_name "somatic_TB21_06450_T1_invert" --normal_min_coverage 5 --tumor_min_coverage 5  --phase_normal --out_dir "/rds/epi2me_workflow/somatic_variation/TB21_06450" -resume -profile singularity  

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hi,
I have noticed on the snv and mod html reports that the sample_name, tumour_bam and normal_bam at the end of the HTML reports do not match the ones I used when I ran the command. I am a bit confused as to which samples were really analysed by the workflow... any help would be greatly appreciated. Many thanks

### Relevant log output

```shell
samples names on the report are : 
bam_normal	/rds/rebasecall_TB23_00177/sorted_dorado_aligned_TB23_00177_tl1_grch38.bam
bam_tumor	/rds/rebasecall_TB23_00177/sorted_dorado_aligned_TB23_00177_tl4_grch38.bam
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by RenzoTale88** [comment] 2024-06-07 07:42
Hi @selmapichot do you mind checking the command line used in the `/rds/epi2me_workflow/somatic_variation/TB21_06450/execution/report.html`?

**Comment by selmapichot** [comment] 2024-06-07 08:30
Hi, the command seems to be the correct one on the /rds/epi2me_workflow/somatic_variation/TB21_06450/execution/report.html with the correct sample. So should I assume that it was the correct sample indeed which was analysed ?

**Comment by RenzoTale88** [comment] 2024-06-07 09:16
Let's have a better look into it. Do you still have the `work` directory produced by the analysis?

**Comment by selmapichot** [comment] 2024-06-07 10:48
yes I do.

**Comment by RenzoTale88** [comment] 2024-06-07 11:21
Ok great! Can you please look for the hash value of a task called `alignment_stats:makeQCreport` in the `Task` table at the end of `/rds/epi2me_workflow/somatic_variation/TB21_06450/execution/report.html`. That value will be the beginning of the path in `work`:
```
ls work/{ insert hash here}*/
```

**Comment by selmapichot** [comment] 2024-06-07 12:12
(tasks table omitted because the dataset is too big)  in the html report ...

**Comment by RenzoTale88** [comment] 2024-06-10 08:54
Ok, then let's try something else. Check the `trace.txt` file instead:
```
grep makeQCreport /rds/epi2me_workflow/somatic_variation/TB21_06450/execution/report.html
```
And retrieve the hash value as described above.

**Comment by RenzoTale88** [comment] 2024-06-25 09:09
@selmapichot any progress with this?

**Comment by selmapichot** [comment] 2024-06-25 09:14
Hi, 
Sorry, couldn't get anything running this command, or maybe I'm not sure what to look for exactly. 
I have run another sample using the somatic_variation wf 3 days ago and I still have the same issue in the report.

**Comment by RenzoTale88** [comment] 2024-06-25 09:29
Thanks for confirming that the issue is still present. We need to figure out what is going on in the process to be able to understand what is causing this issue. Do you still have the work directory generated by the workflow?

**Comment by selmapichot** [comment] 2024-06-25 11:16
Yes, I still have the work directory.

**Comment by RenzoTale88** [comment] 2024-06-25 15:21
Ok that's good. The first thing is check the content of `execution/report.html` in the output directory. In there, there should be a table with the list of the processes executed. You need to find the row referring to the `makeQCreport` process, as we will need the hash reported there.

**Comment by RenzoTale88** [comment] 2024-06-26 12:51
@selmapichot alternatively, do you mind sharing the file `execution/trace.txt` in the output directory?

**Comment by selmapichot** [comment] 2024-06-26 13:06
[trace.txt](https://github.com/user-attachments/files/15988713/trace.txt)

Yes of course, please find it attached.

**Comment by RenzoTale88** [comment] 2024-06-26 13:40
Based on the `trace.txt` file, you haven't run the reporting script, and therefore you shouldn't have the report at all. I can see that you have a lot of cached processes.

Do you mind updating the workflow to the latest version and try again without resuming the process?
I'd suggest to drop the workflow first, then rerun it from clean (without `-resume`)
```
nextflow drop epi2me-labs/wf-somatic-variation
nextflow run epi2me-labs/wf-somatic-variation -r v1.2.2 ...
```
Let me know if the workflow runs the `makeQCreport` process.

Andrea

**Comment by RenzoTale88** [comment] 2024-07-11 10:07
@selmapichot did you try the mentioned suggestion?

**Comment by RenzoTale88** [comment] 2024-08-14 12:48
@selmapichot any progress on this?

**Comment by RenzoTale88** [comment] 2024-08-23 11:23
@selmapichot closing this as there has been no updates in a long time. Please, do get in touch again or reopen the ticket if you need further support with this.

**Closed by RenzoTale88** 2024-08-23 11:23 UTC
